// export const baseURL = 'https://map.noncegeek.com/tai_shang_world_generator/api/v1'
export const baseURL = 'http://localhost:4000/tai_shang_world_generator/api/v1'
export const lastBlockNumURL = baseURL + '/get_last_block_num'
export const genMapURL =  baseURL + '/gen_map'
export const loadChainURL = baseURL + '/character/get_info'
export const loadCharacterURL = baseURL + '/character/load_character'
export const eventsURL = baseURL + '/events'